wget http://files.grumbler.org/pub/dictd/1000pbio.dict.dz
wget http://files.grumbler.org/pub/dictd/1000pbio.index
wget http://files.grumbler.org/pub/dictd/abr1w.dict.dz
wget http://files.grumbler.org/pub/dictd/abr1w.index
wget http://files.grumbler.org/pub/dictd/ahiezer.dict.dz
wget http://files.grumbler.org/pub/dictd/ahiezer.index
wget http://files.grumbler.org/pub/dictd/aviation.dict.dz
wget http://files.grumbler.org/pub/dictd/aviation.index
wget http://files.grumbler.org/pub/dictd/beslov.dict.dz
wget http://files.grumbler.org/pub/dictd/beslov.index
wget http://files.grumbler.org/pub/dictd/biology.dict.dz
wget http://files.grumbler.org/pub/dictd/biology.index
wget http://files.grumbler.org/pub/dictd/brok_and_efr.dict.dz
wget http://files.grumbler.org/pub/dictd/brok_and_efr.index
wget http://files.grumbler.org/pub/dictd/bus.dict.dz
wget http://files.grumbler.org/pub/dictd/bus.index
wget http://files.grumbler.org/pub/dictd/church.dict.dz
wget http://files.grumbler.org/pub/dictd/church.index
wget http://files.grumbler.org/pub/dictd/compbe.dict.dz
wget http://files.grumbler.org/pub/dictd/compbe.index
wget http://files.grumbler.org/pub/dictd/dalf.dict.dz
wget http://files.grumbler.org/pub/dictd/dalf.index
wget http://files.grumbler.org/pub/dictd/deutsch_de-ru.dict.dz
wget http://files.grumbler.org/pub/dictd/deutsch_de-ru.index
wget http://files.grumbler.org/pub/dictd/deutsch_ru-de.dict.dz
wget http://files.grumbler.org/pub/dictd/deutsch_ru-de.index
wget http://files.grumbler.org/pub/dictd/engcom.dict.dz
wget http://files.grumbler.org/pub/dictd/engcom.index
wget http://files.grumbler.org/pub/dictd/estonian_et-ru.dict.dz
wget http://files.grumbler.org/pub/dictd/estonian_et-ru.index
wget http://files.grumbler.org/pub/dictd/estonian_et_ru.dict.dz
wget http://files.grumbler.org/pub/dictd/estonian_et_ru.index
wget http://files.grumbler.org/pub/dictd/ethnographic.dict.dz
wget http://files.grumbler.org/pub/dictd/ethnographic.index
wget http://files.grumbler.org/pub/dictd/findict.dict.dz
wget http://files.grumbler.org/pub/dictd/findict.index
wget http://files.grumbler.org/pub/dictd/foldoc.dict.dz
wget http://files.grumbler.org/pub/dictd/foldoc.index
wget http://files.grumbler.org/pub/dictd/geology_en-ru.dict.dz
wget http://files.grumbler.org/pub/dictd/geology_en-ru.index
wget http://files.grumbler.org/pub/dictd/geology_ru-en.dict.dz
wget http://files.grumbler.org/pub/dictd/geology_ru-en.index
wget http://files.grumbler.org/pub/dictd/hi127.dict.dz
wget http://files.grumbler.org/pub/dictd/hi127.index
wget http://files.grumbler.org/pub/dictd/idioms.dict.dz
wget http://files.grumbler.org/pub/dictd/idioms.index
wget http://files.grumbler.org/pub/dictd/komi-rus.dict.dz
wget http://files.grumbler.org/pub/dictd/komi-rus.index
wget http://files.grumbler.org/pub/dictd/korolew_en-ru.dict.dz
wget http://files.grumbler.org/pub/dictd/korolew_en-ru.index
wget http://files.grumbler.org/pub/dictd/korolew_ru-en.dict.dz
wget http://files.grumbler.org/pub/dictd/korolew_ru-en.index
wget http://files.grumbler.org/pub/dictd/latrus.dict.dz
wget http://files.grumbler.org/pub/dictd/latrus.index
wget http://files.grumbler.org/pub/dictd/magus.dict.dz
wget http://files.grumbler.org/pub/dictd/magus.index
wget http://files.grumbler.org/pub/dictd/mech_mime.dict.dz
wget http://files.grumbler.org/pub/dictd/mech_mime.index
wget http://files.grumbler.org/pub/dictd/mech_nomime.dict.dz
wget http://files.grumbler.org/pub/dictd/mech_nomime.index
wget http://files.grumbler.org/pub/dictd/meddict.dict.dz
wget http://files.grumbler.org/pub/dictd/meddict.index
wget http://files.grumbler.org/pub/dictd/mueller24.dict.dz
wget http://files.grumbler.org/pub/dictd/mueller24.index
wget http://files.grumbler.org/pub/dictd/mueller7.dict.dz
wget http://files.grumbler.org/pub/dictd/mueller7.index
wget http://files.grumbler.org/pub/dictd/muiswerk.dict.dz
wget http://files.grumbler.org/pub/dictd/muiswerk.index
wget http://files.grumbler.org/pub/dictd/ozhegov.dict.dz
wget http://files.grumbler.org/pub/dictd/ozhegov.index
wget http://files.grumbler.org/pub/dictd/ozhshv.dict.dz
wget http://files.grumbler.org/pub/dictd/ozhshv.index
wget http://files.grumbler.org/pub/dictd/religion.dict.dz
wget http://files.grumbler.org/pub/dictd/religion.index
wget http://files.grumbler.org/pub/dictd/sc-abbr.dict.dz
wget http://files.grumbler.org/pub/dictd/sc-abbr.index
wget http://files.grumbler.org/pub/dictd/sdict_fi-ru.dict.dz
wget http://files.grumbler.org/pub/dictd/sdict_fi-ru.index
wget http://files.grumbler.org/pub/dictd/sdict_ru-en.dict.dz
wget http://files.grumbler.org/pub/dictd/sdict_ru-en.index
wget http://files.grumbler.org/pub/dictd/ses.dict.dz
wget http://files.grumbler.org/pub/dictd/ses.index
wget http://files.grumbler.org/pub/dictd/sinyagin_abbrev.dict.dz
wget http://files.grumbler.org/pub/dictd/sinyagin_abbrev.index
wget http://files.grumbler.org/pub/dictd/sinyagin_alexeymavrin.dict.dz
wget http://files.grumbler.org/pub/dictd/sinyagin_alexeymavrin.index
wget http://files.grumbler.org/pub/dictd/sinyagin_business.dict.dz
wget http://files.grumbler.org/pub/dictd/sinyagin_business.index
wget http://files.grumbler.org/pub/dictd/sinyagin_computer.dict.dz
wget http://files.grumbler.org/pub/dictd/sinyagin_computer.index
wget http://files.grumbler.org/pub/dictd/sinyagin_general_er.dict.dz
wget http://files.grumbler.org/pub/dictd/sinyagin_general_er.index
wget http://files.grumbler.org/pub/dictd/sinyagin_general_re.dict.dz
wget http://files.grumbler.org/pub/dictd/sinyagin_general_re.index
wget http://files.grumbler.org/pub/dictd/slovnyk_be-en.dict.dz
wget http://files.grumbler.org/pub/dictd/slovnyk_be-en.index
wget http://files.grumbler.org/pub/dictd/slovnyk_be-pl.dict.dz
wget http://files.grumbler.org/pub/dictd/slovnyk_be-pl.index
wget http://files.grumbler.org/pub/dictd/slovnyk_be-ru.dict.dz
wget http://files.grumbler.org/pub/dictd/slovnyk_be-ru.index
wget http://files.grumbler.org/pub/dictd/slovnyk_be-uk.dict.dz
wget http://files.grumbler.org/pub/dictd/slovnyk_be-uk.index
wget http://files.grumbler.org/pub/dictd/slovnyk_en-be.dict.dz
wget http://files.grumbler.org/pub/dictd/slovnyk_en-be.index
wget http://files.grumbler.org/pub/dictd/slovnyk_en-pl.dict.dz
wget http://files.grumbler.org/pub/dictd/slovnyk_en-pl.index
wget http://files.grumbler.org/pub/dictd/slovnyk_en-ru.dict.dz
wget http://files.grumbler.org/pub/dictd/slovnyk_en-ru.index
wget http://files.grumbler.org/pub/dictd/slovnyk_en-uk.dict.dz
wget http://files.grumbler.org/pub/dictd/slovnyk_en-uk.index
wget http://files.grumbler.org/pub/dictd/slovnyk_pl-be.dict.dz
wget http://files.grumbler.org/pub/dictd/slovnyk_pl-be.index
wget http://files.grumbler.org/pub/dictd/slovnyk_pl-en.dict.dz
wget http://files.grumbler.org/pub/dictd/slovnyk_pl-en.index
wget http://files.grumbler.org/pub/dictd/slovnyk_pl-ru.dict.dz
wget http://files.grumbler.org/pub/dictd/slovnyk_pl-ru.index
wget http://files.grumbler.org/pub/dictd/slovnyk_pl-uk.dict.dz
wget http://files.grumbler.org/pub/dictd/slovnyk_pl-uk.index
wget http://files.grumbler.org/pub/dictd/slovnyk_ru-be.dict.dz
wget http://files.grumbler.org/pub/dictd/slovnyk_ru-be.index
wget http://files.grumbler.org/pub/dictd/slovnyk_ru-en.dict.dz
wget http://files.grumbler.org/pub/dictd/slovnyk_ru-en.index
wget http://files.grumbler.org/pub/dictd/slovnyk_ru-pl.dict.dz
wget http://files.grumbler.org/pub/dictd/slovnyk_ru-pl.index
wget http://files.grumbler.org/pub/dictd/slovnyk_ru-uk.dict.dz
wget http://files.grumbler.org/pub/dictd/slovnyk_ru-uk.index
wget http://files.grumbler.org/pub/dictd/slovnyk_uk-be.dict.dz
wget http://files.grumbler.org/pub/dictd/slovnyk_uk-be.index
wget http://files.grumbler.org/pub/dictd/slovnyk_uk-en.dict.dz
wget http://files.grumbler.org/pub/dictd/slovnyk_uk-en.index
wget http://files.grumbler.org/pub/dictd/slovnyk_uk-pl.dict.dz
wget http://files.grumbler.org/pub/dictd/slovnyk_uk-pl.index
wget http://files.grumbler.org/pub/dictd/slovnyk_uk-ru.dict.dz
wget http://files.grumbler.org/pub/dictd/slovnyk_uk-ru.index
wget http://files.grumbler.org/pub/dictd/smiley.dict.dz
wget http://files.grumbler.org/pub/dictd/smiley.index
wget http://files.grumbler.org/pub/dictd/sokrat_en-ru.dict.dz
wget http://files.grumbler.org/pub/dictd/sokrat_en-ru.index
wget http://files.grumbler.org/pub/dictd/sokrat_ru-en.dict.dz
wget http://files.grumbler.org/pub/dictd/sokrat_ru-en.index
wget http://files.grumbler.org/pub/dictd/swedish_ru-sv.dict.dz
wget http://files.grumbler.org/pub/dictd/swedish_ru-sv.index
wget http://files.grumbler.org/pub/dictd/swedish_sv-ru.dict.dz
wget http://files.grumbler.org/pub/dictd/swedish_sv-ru.index
wget http://files.grumbler.org/pub/dictd/teo.dict.dz
wget http://files.grumbler.org/pub/dictd/teo.index
wget http://files.grumbler.org/pub/dictd/ushakov.dict.dz
wget http://files.grumbler.org/pub/dictd/ushakov.index
wget http://files.grumbler.org/pub/dictd/zhelezyaki_abbr.dict.dz
wget http://files.grumbler.org/pub/dictd/zhelezyaki_abbr.index
wget http://files.grumbler.org/pub/dictd/zhelezyaki_analogs.dict.dz
wget http://files.grumbler.org/pub/dictd/zhelezyaki_analogs.index
