wget http://dictd.xdsl.by/dicts/1000pbio.dict.dz
wget http://dictd.xdsl.by/dicts/1000pbio.index
wget http://dictd.xdsl.by/dicts/abr1w.dict.dz
wget http://dictd.xdsl.by/dicts/abr1w.index
wget http://dictd.xdsl.by/dicts/ahiezer.dict.dz
wget http://dictd.xdsl.by/dicts/ahiezer.index
wget http://dictd.xdsl.by/dicts/aviation.dict.dz
wget http://dictd.xdsl.by/dicts/aviation.index
wget http://dictd.xdsl.by/dicts/beslov.dict.dz
wget http://dictd.xdsl.by/dicts/beslov.index
wget http://dictd.xdsl.by/dicts/biology.dict.dz
wget http://dictd.xdsl.by/dicts/biology.index
wget http://dictd.xdsl.by/dicts/brok_and_efr.dict.dz
wget http://dictd.xdsl.by/dicts/brok_and_efr.index
wget http://dictd.xdsl.by/dicts/bus.dict.dz
wget http://dictd.xdsl.by/dicts/bus.index
wget http://dictd.xdsl.by/dicts/church.dict.dz
wget http://dictd.xdsl.by/dicts/church.index
wget http://dictd.xdsl.by/dicts/compbe.dict.dz
wget http://dictd.xdsl.by/dicts/compbe.index
wget http://dictd.xdsl.by/dicts/dalf.dict.dz
wget http://dictd.xdsl.by/dicts/dalf.index
wget http://dictd.xdsl.by/dicts/deutsch_de-ru.dict.dz
wget http://dictd.xdsl.by/dicts/deutsch_de-ru.index
wget http://dictd.xdsl.by/dicts/deutsch_ru-de.dict.dz
wget http://dictd.xdsl.by/dicts/deutsch_ru-de.index
wget http://dictd.xdsl.by/dicts/engcom.dict.dz
wget http://dictd.xdsl.by/dicts/engcom.index
wget http://dictd.xdsl.by/dicts/estonian_et-ru.dict.dz
wget http://dictd.xdsl.by/dicts/estonian_et-ru.index
wget http://dictd.xdsl.by/dicts/estonian_et_ru.dict.dz
wget http://dictd.xdsl.by/dicts/estonian_et_ru.index
wget http://dictd.xdsl.by/dicts/ethnographic.dict.dz
wget http://dictd.xdsl.by/dicts/ethnographic.index
wget http://dictd.xdsl.by/dicts/findict.dict.dz
wget http://dictd.xdsl.by/dicts/findict.index
wget http://dictd.xdsl.by/dicts/foldoc.dict.dz
wget http://dictd.xdsl.by/dicts/foldoc.index
wget http://dictd.xdsl.by/dicts/geology_en-ru.dict.dz
wget http://dictd.xdsl.by/dicts/geology_en-ru.index
wget http://dictd.xdsl.by/dicts/geology_ru-en.dict.dz
wget http://dictd.xdsl.by/dicts/geology_ru-en.index
wget http://dictd.xdsl.by/dicts/hi127.dict.dz
wget http://dictd.xdsl.by/dicts/hi127.index
wget http://dictd.xdsl.by/dicts/idioms.dict.dz
wget http://dictd.xdsl.by/dicts/idioms.index
wget http://dictd.xdsl.by/dicts/komi-rus.dict.dz
wget http://dictd.xdsl.by/dicts/komi-rus.index
wget http://dictd.xdsl.by/dicts/korolew_en-ru.dict.dz
wget http://dictd.xdsl.by/dicts/korolew_en-ru.index
wget http://dictd.xdsl.by/dicts/korolew_ru-en.dict.dz
wget http://dictd.xdsl.by/dicts/korolew_ru-en.index
wget http://dictd.xdsl.by/dicts/latrus.dict.dz
wget http://dictd.xdsl.by/dicts/latrus.index
wget http://dictd.xdsl.by/dicts/magus.dict.dz
wget http://dictd.xdsl.by/dicts/magus.index
wget http://dictd.xdsl.by/dicts/mech_mime.dict.dz
wget http://dictd.xdsl.by/dicts/mech_mime.index
wget http://dictd.xdsl.by/dicts/mech_nomime.dict.dz
wget http://dictd.xdsl.by/dicts/mech_nomime.index
wget http://dictd.xdsl.by/dicts/meddict.dict.dz
wget http://dictd.xdsl.by/dicts/meddict.index
wget http://dictd.xdsl.by/dicts/mueller24.dict.dz
wget http://dictd.xdsl.by/dicts/mueller24.index
wget http://dictd.xdsl.by/dicts/mueller7.dict.dz
wget http://dictd.xdsl.by/dicts/mueller7.index
wget http://dictd.xdsl.by/dicts/muiswerk.dict.dz
wget http://dictd.xdsl.by/dicts/muiswerk.index
wget http://dictd.xdsl.by/dicts/ozhegov.dict.dz
wget http://dictd.xdsl.by/dicts/ozhegov.index
wget http://dictd.xdsl.by/dicts/ozhshv.dict.dz
wget http://dictd.xdsl.by/dicts/ozhshv.index
wget http://dictd.xdsl.by/dicts/religion.dict.dz
wget http://dictd.xdsl.by/dicts/religion.index
wget http://dictd.xdsl.by/dicts/sc-abbr.dict.dz
wget http://dictd.xdsl.by/dicts/sc-abbr.index
wget http://dictd.xdsl.by/dicts/sdict_fi-ru.dict.dz
wget http://dictd.xdsl.by/dicts/sdict_fi-ru.index
wget http://dictd.xdsl.by/dicts/sdict_ru-en.dict.dz
wget http://dictd.xdsl.by/dicts/sdict_ru-en.index
wget http://dictd.xdsl.by/dicts/ses.dict.dz
wget http://dictd.xdsl.by/dicts/ses.index
wget http://dictd.xdsl.by/dicts/sinyagin_abbrev.dict.dz
wget http://dictd.xdsl.by/dicts/sinyagin_abbrev.index
wget http://dictd.xdsl.by/dicts/sinyagin_alexeymavrin.dict.dz
wget http://dictd.xdsl.by/dicts/sinyagin_alexeymavrin.index
wget http://dictd.xdsl.by/dicts/sinyagin_business.dict.dz
wget http://dictd.xdsl.by/dicts/sinyagin_business.index
wget http://dictd.xdsl.by/dicts/sinyagin_computer.dict.dz
wget http://dictd.xdsl.by/dicts/sinyagin_computer.index
wget http://dictd.xdsl.by/dicts/sinyagin_general_er.dict.dz
wget http://dictd.xdsl.by/dicts/sinyagin_general_er.index
wget http://dictd.xdsl.by/dicts/sinyagin_general_re.dict.dz
wget http://dictd.xdsl.by/dicts/sinyagin_general_re.index
wget http://dictd.xdsl.by/dicts/slovnyk_be-en.dict.dz
wget http://dictd.xdsl.by/dicts/slovnyk_be-en.index
wget http://dictd.xdsl.by/dicts/slovnyk_be-pl.dict.dz
wget http://dictd.xdsl.by/dicts/slovnyk_be-pl.index
wget http://dictd.xdsl.by/dicts/slovnyk_be-ru.dict.dz
wget http://dictd.xdsl.by/dicts/slovnyk_be-ru.index
wget http://dictd.xdsl.by/dicts/slovnyk_be-uk.dict.dz
wget http://dictd.xdsl.by/dicts/slovnyk_be-uk.index
wget http://dictd.xdsl.by/dicts/slovnyk_en-be.dict.dz
wget http://dictd.xdsl.by/dicts/slovnyk_en-be.index
wget http://dictd.xdsl.by/dicts/slovnyk_en-pl.dict.dz
wget http://dictd.xdsl.by/dicts/slovnyk_en-pl.index
wget http://dictd.xdsl.by/dicts/slovnyk_en-ru.dict.dz
wget http://dictd.xdsl.by/dicts/slovnyk_en-ru.index
wget http://dictd.xdsl.by/dicts/slovnyk_en-uk.dict.dz
wget http://dictd.xdsl.by/dicts/slovnyk_en-uk.index
wget http://dictd.xdsl.by/dicts/slovnyk_pl-be.dict.dz
wget http://dictd.xdsl.by/dicts/slovnyk_pl-be.index
wget http://dictd.xdsl.by/dicts/slovnyk_pl-en.dict.dz
wget http://dictd.xdsl.by/dicts/slovnyk_pl-en.index
wget http://dictd.xdsl.by/dicts/slovnyk_pl-ru.dict.dz
wget http://dictd.xdsl.by/dicts/slovnyk_pl-ru.index
wget http://dictd.xdsl.by/dicts/slovnyk_pl-uk.dict.dz
wget http://dictd.xdsl.by/dicts/slovnyk_pl-uk.index
wget http://dictd.xdsl.by/dicts/slovnyk_ru-be.dict.dz
wget http://dictd.xdsl.by/dicts/slovnyk_ru-be.index
wget http://dictd.xdsl.by/dicts/slovnyk_ru-en.dict.dz
wget http://dictd.xdsl.by/dicts/slovnyk_ru-en.index
wget http://dictd.xdsl.by/dicts/slovnyk_ru-pl.dict.dz
wget http://dictd.xdsl.by/dicts/slovnyk_ru-pl.index
wget http://dictd.xdsl.by/dicts/slovnyk_ru-uk.dict.dz
wget http://dictd.xdsl.by/dicts/slovnyk_ru-uk.index
wget http://dictd.xdsl.by/dicts/slovnyk_uk-be.dict.dz
wget http://dictd.xdsl.by/dicts/slovnyk_uk-be.index
wget http://dictd.xdsl.by/dicts/slovnyk_uk-en.dict.dz
wget http://dictd.xdsl.by/dicts/slovnyk_uk-en.index
wget http://dictd.xdsl.by/dicts/slovnyk_uk-pl.dict.dz
wget http://dictd.xdsl.by/dicts/slovnyk_uk-pl.index
wget http://dictd.xdsl.by/dicts/slovnyk_uk-ru.dict.dz
wget http://dictd.xdsl.by/dicts/slovnyk_uk-ru.index
wget http://dictd.xdsl.by/dicts/smiley.dict.dz
wget http://dictd.xdsl.by/dicts/smiley.index
wget http://dictd.xdsl.by/dicts/sokrat_en-ru.dict.dz
wget http://dictd.xdsl.by/dicts/sokrat_en-ru.index
wget http://dictd.xdsl.by/dicts/sokrat_ru-en.dict.dz
wget http://dictd.xdsl.by/dicts/sokrat_ru-en.index
wget http://dictd.xdsl.by/dicts/swedish_ru-sv.dict.dz
wget http://dictd.xdsl.by/dicts/swedish_ru-sv.index
wget http://dictd.xdsl.by/dicts/swedish_sv-ru.dict.dz
wget http://dictd.xdsl.by/dicts/swedish_sv-ru.index
wget http://dictd.xdsl.by/dicts/teo.dict.dz
wget http://dictd.xdsl.by/dicts/teo.index
wget http://dictd.xdsl.by/dicts/ushakov.dict.dz
wget http://dictd.xdsl.by/dicts/ushakov.index
wget http://dictd.xdsl.by/dicts/zhelezyaki_abbr.dict.dz
wget http://dictd.xdsl.by/dicts/zhelezyaki_abbr.index
wget http://dictd.xdsl.by/dicts/zhelezyaki_analogs.dict.dz
wget http://dictd.xdsl.by/dicts/zhelezyaki_analogs.index
