sudo apt-get install wmctrl
sudo apt-get install samba
sudo apt-get install smbfs
sudo apt-get install texinfo
sudo apt-get install automake autoconf
sudo apt-get install python2.7-dev
sudo apt-get install git
sudo apt-get install etckeeper
sudo apt-get install checkinstall
sudo apt-get install cvs
sudo apt-get install subversion
sudo apt-get install git-core
sudo apt-get install git-svn
sudo apt-get install bzr
sudo apt-get install mercurial

sudo apt-get install build-essential cdbs fakeroot dh-make debhelper debconf libstdc++6 dkms libqtgui4 wget execstack libelfg0 dh-modaliases linux-headers-generic xserver-xorg-core libgcc1 ia32-libs-multiarch:i386 lib32gcc1 libc6-i386
sudo apt-get install compizconfig-settings-manager
sudo apt-get install dictd
sudo apt-get install dict
sudo apt-get install libnotify-bin
sudo apt-get install xfce4-notifyd
sudo apt-get install w3m
sudo apt-get install magit
sudo apt-get install ffmpeg lame
sudo apt-get install bitlbee
sudo apt-get install expect
sudo apt-get install mailutils
sudo apt-get install ipython
sudo apt-get install python-sympy
sudo apt-get install python-numpy
sudo apt-get install python-scipy
sudo apt-get install python-gnuplot
sudo apt-get install python-tk
sudo apt-get install python-pmw
sudo apt-get install python2.7-doc
sudo apt-get install python-setuptools
sudo apt-get install python-pip
sudo apt-get install python3
sudo apt-get install python3-dev
sudo apt-get install python3-setuptools
sudo apt-get install libopenmpi-dev
sudo apt-get install gnutls-bin
sudo apt-get install libtool
sudo apt-get install clisp
sudo apt-get install sbcl
sudo apt-get install texlive
sudo apt-get install tetex-brev
sudo apt-get install texlive-latex-extra
sudo apt-get install texlive-lang-cyrillic
sudo apt-get install tex4ht
sudo apt-get install auctex
sudo apt-get install xpdf
sudo apt-get install gfortran
sudo apt-get install fort77
sudo apt-get install flex
sudo apt-get install scalable-cyrfonts-tex
sudo apt-get install uuid
sudo apt-get install mpich2
sudo apt-get install grepmail
sudo apt-get install aspell-ru
sudo apt-get install ruby-dev
sudo apt-get install figlet
