python gscholar.py "Функциональный анализ"
exit
python gscholar.py "The Numerical Solution of Integral Equations of the Second Kind"
python gscholar.py "Методы решения некорректных задач"
python gscholar.py "Численное решение интегрального уравнения I рода с логарифмической особенностью"
python gscholar.py "Численное решение интегрального уравнения I рода с логарифмической особенностью методом интерполяции и коллокации"
python gscholar.py "Интегральные уравнения в краевых задачах электродинамики"
python gscholar.py "A discrete Galerkin method for first kind integral equation with a logarithmic kernel"
python gscholar.py "On the numerical solution of a logarithmic integral equation of the first kind for the Helmholtz equation"
python gscholar.py "Численное решение интегрального уравнения I рода со слабой особенностью для плотности потенциала простого слоя"
python gscholar.py "Интегральные уравнения задач дифракции"
python gscholar.py "Методы граничных элементов"
python gscholar.py "Исследование и численное решение интегральных уравнений трёхмерных стационарных задач дифракции акустических волн"
python gscholar.py "Численное решение трёхмерной стационарной задачи дифракции акустических волн на упругом включении"
python gscholar.py "GMRES: A generalized minimal residual algorithm for solving nonsymmetric linear systems"
python gscholar.py "Iterative methods for sparse linear systems"
python gscholar.py "Численное решение краевых задач акустики на спектре методом граничных интегральных уравнений"
python gscholar.py "On Numerical Solution of Three-dimensional Diffraction Problems in the Integral Form"
python gscholar.py "On Numerical Solution of Integral Equations for Three-dimensional Diffraction Problems"
python gscholar.py "О численном решении задач Дирихле потенциалами простого слоя"
python gscholar.py "Применение графического интерфейса пользователя вычислительного кластера на примере решения краевых задач акустики"
python gscholar.py "Численное решение трехмерной стационарной задачи дифракции упругих волн на основе векторного интегрального уравнения Фредгольма 1 рода"
python gscholar.py "Решение трехмерной задачи дифракции электромагнитных волн при помощи интегральных уравнений с минимальным количеством неизвестных функций"
python gscholar.py "Решение пространственной стационарной задачи дифракции упругих волн на основе векторного интегрального уравнения фредгольма I рода с одной неизвестной вектор-функцией"
python gscholar.py "Численное решение трехмерной стационарной задачи дифракции акустических волн"
python gscholar.py "Численное решение трехмерной стационарной задачи дифракции упругих волн"
python gscholar.py "Задача оптимального управления для стационарных уравнений дифракции упругих волн"
python gscholar.py "Постановка и решение задачи  об устойчивости несвязного дна канала"
python gscholar.py "О развитии возмущений песчаного дна канала"
python gscholar.py "Об устойчивости песчаного дна канала постоянной ширины"
python gscholar.py "Русловые процессы в равнинных реках с несвязным руслом"
python gscholar.py "Проблемы исследования русловых процессов в равнинных реках с песчаным дном"
python gscholar.py "Анализ донных деформаций несвязного дна канала в нижнем бьефе гидроузла"
python gscholar.py "Модель деформирования берегового склона для рек с песчаным дном"
python gscholar.py "О неравновесных деформациях несвязного дна канала"
python gscholar.py "Об образовании песчаных волн на дне потока конечной ширины"
python gscholar.py "Об набегании осветленного потока на несвязное дно"
python gscholar.py "Об математическом моделировании русловых процессов в среднем течении реки Амур"
python gscholar.py "Двухслойная модель русловых деформаций, для неоднородного донного материала"
python gscholar.py "Исследование характеристик материала с поверхностным градиентом упругих свойств"
python gscholar.py "Численный алгоритм математического моделирования задачи тепломассопереноса материала при электрофизическом воздействии"
python gscholar.py "Моделирование неравновесных электроискровых процессов"
python gscholar.py "О сходимости метода Удзавы с модифицированным функционалом Лагранжа в вариационных неравенствах механики"
python gscholar.py "Об устойчивом методе решения модельной задачи с заданным трением"
python gscholar.py "О сглаживающемся методе двойственности для решения модельной задачи с трением"
python gscholar.py "Потери энергии при прохождении поляризованной волны через произвольную границу двух сред"
python gscholar.py "Метод контроля разупрочнения массива горных пород"
python gscholar.py "Параллельные алгоритмы роя частиц в решении обратных задач электромагнитных зондирований"
python gscholar.py "Вычислительные математика и техника в разведочной геофизике: Справочник геофизика"
python gscholar.py "Генетические алгоритмы решения обратных задач электромагнитного зондирования"
python gscholar.py "Моделирование электромагнитных полей в слоистых средах с включениями"
python gscholar.py "The particle swarm: Explosion, stability and convergence in a multi-dimensional complex space"
python gscholar.py "Неразрушающий контроль"
python gscholar.py "Исследование рассеяния ультразвука в металлах"
python gscholar.py "Поглощение и диффузное рассеяния ультразвука в металлах"
python gscholar.py "Применение ультразвука для исследования структуры сталей"
python gscholar.py "Дисперсия упругих волн в композиционных материалах"
python gscholar.py "К теории распространения ультразвуковых волн в поликристаллах"
python gscholar.py "Исследование рассеяния ультразвука с учетом статистики распределения величин зерен поликристаллических металлов"
python gscholar.py "Дисперсия скорости и рассеяние поперечных ультразвуковых волн в композиционных материалах"
python gscholar.py "Дисперсия скорости и рассеяние продольных ультразвуковых волн в композиционных материалах"
python gscholar.py "К расчету коэффициента затухания упругих волн в поликристаллических средах"
python gscholar.py "Метрологические характеристики средств измерения и их практическое применение"
python gscholar.py "Прецизионные акустические измерения оптическими и емкостными методами"
python gscholar.py "О качестве образцов для ультразвуковых измерений"
python gscholar.py "Нелинейные явления при распространении упругих волн в твердых телах"
python gscholar.py "Ультразвуковые методы в физике твердого тела"
python gscholar.py "Генетический алгоритм составления расписания выполнения параллельных заданий в распределенной вычислительной системе"
python gscholar.py "Genetic Algorithm Based Parallel Jobs Scheduling"
python gscholar.py "Об интеграции диспетчера заданий в GRID-инструментарий GLOBUS TOOLKIT"
python gscholar.py "Система планирования выполнения заданий в Grid, основанная на составлении расписаний генетическим алгоритмом"
python gscholar.py " Механизм уведомлений о событиях в системе мониторинга"
python gscholar.py "The Network Weather Service: A Distributed Resource Performance Forecasting Service for Metacomputing"
python gscholar.py "Condor-G: A Computation Management Agent for Multi-Institutional Grids"
python gscholar.py "Software Agents"
python gscholar.py "Системы поддержки принятия решений: современное состояние и перспективы развития"
python gscholar.py "О некоторых вопросах обучения автоматов"
python gscholar.py "Математические задачи системного анализа"
python gscholar.py "Некоторые вопросы надежности и контроля управляющих систем"
python gscholar.py "Мониторинг вычислительного кластера с использованием Java-технологий"
python gscholar.py "Расширяемая система мониторинга вычислительного кластера"
python gscholar.py "Трехуровневая система мониторинга расширенной функциональности"
python gscholar.py " Удаленный доступ к вычислительному кластеру ВЦ ДВО РАН"
python gscholar.py "Вычислительный кластер бездисковых рабочих станций"
python gscholar.py "Нейросетевые компоненты мониторинга вычислительного кластера"
python gscholar.py " Модульная нейросетевая система мониторинга вычислительного кластера"
python gscholar.py "Теория и практика"
python gscholar.py "Нейронные сети: полный курс"
python gscholar.py "Савин"
python gscholar.py "Исследование производительности четырехпроцессорных узлов в составе вычислительного кластера"
python gscholar.py "Зависимость производительности передачи сообщений MPI от порядка распределения процессов в четырехпроцессорном узле вычислительного кластера"
python gscholar.py "Гетерогенный вычислительный кластер ВЦ ДВО РАН"
python gscholar.py "Оценка производительности вычислительного кластера на четырехъядерных процессорах"
python gscholar.py "Сравнительный анализ эффективности программного обеспечения для вычислительных кластеров"
python gscholar.py "A stationary nonlinear transport problem"
python gscholar.py "A Nonlinear Pricing Model with Lump-Sum Transportation Costs"
python gscholar.py "An Evolution Program for Non-Linear Transportation Problems"
python gscholar.py "An Evolution Program for Non-Linear Transportation Problems"
python gscholar.py "Genetic Algorithm for the Transportation Problem with Discontinuous Piecewise Linear Cost Function"
python gscholar.py "A Nonstandard Genetic Algorithm for the Nonlinear Transportation Problem"
python gscholar.py "Implementation Of An Ant Colony System With Local Search For The Vehicle Routing Problem With Capacity And Time Windows (CVRPTW)"
python gscholar.py "Ant colony optimization techniques for the vehicle routing problem"
python gscholar.py "Applying the Ant System to the Vehicle Routing Problem"
python gscholar.py "Metaheuristic Approaches for the Vehicle Routing Problem with Time Windows: A Survey"
python gscholar.py "Аналитические методы теории волноводов"
python gscholar.py "Рассеяние волн локальными неоднородностями в сплошных средах"
python gscholar.py "Ультразвуковые методы в физике твердого тела"
python gscholar.py "Теория дифракции"
python gscholar.py "Grundprobleme der Mathematischen Theorie Electromagnetisher Schwingungen"
python gscholar.py "A Finite Element Method for Some Integral Equations of the Ftrst Kind"
python gscholar.py "Теория возмущений и асимптотические методы"
python gscholar.py "Спектральные свойства задач дифракции"
python gscholar.py "Асимптотические методы в задачах дифракции коротких волн"
python gscholar.py "Теория разностных схем"
python gscholar.py "Методы вычислительной математики"
python gscholar.py "Введение в проекционно-сеточные методы"
python gscholar.py "Применение метода граничных интегральных уравнений к теории волн на поверхности воды"
python gscholar.py "An Outer Boundary Integral Equation Applied to an Transient Wave Scattering in an Inhomogeneous Medium"
python gscholar.py "О приближенном решении задач математической физики"
python gscholar.py "Численные методы в теории дифракции"
python gscholar.py "Приближение функций многих переменных антенным потенциалом"
python gscholar.py "Дифракция на ограниченном теле"
python gscholar.py "Численное решение двумерной задачи дифракции упругой волны на упругом теле методом потенциалов"
python gscholar.py "Метод расчета плоского электромагнитного поля в среде со слоем переменной толщины"
python gscholar.py "Задача об излучении электромагнитных волн в слоистой среде с осевой симметрией"
python gscholar.py "On Single Integral Equations for the Transmission Problem of Accoustics"
python gscholar.py "Boundary Integral Equations for the Scattering of Electromagnetic Waves by a Homogeneous Dielectric Obstacle"
python gscholar.py "Single Integral Equation for Wave Scattering"
python gscholar.py "Вычислительные методы в электродинамике"
python gscholar.py "Интегральные уравнения в краевых задачах электродинамики"
python gscholar.py "Метод расчета электромагнитных полей в плоско-параллельной слоистой среде с локальными неоднородностями"
python gscholar.py "Методы интегральных уравнений в теории рассеяния"
python gscholar.py "Решение трехмерной задачи дифракции методом антенных потенциалов"
python gscholar.py "Граничные задачи теории колебаний и интегральные уравнения"
python gscholar.py "Исследование и численные методы решения задач дифракции электромагнитных волн в локально неоднородных средах"
python gscholar.py "Трехмерные задачи математической теории упругости"
python gscholar.py "Grundprobleme der Mathematischen Teorie Elec tromagnetischer Schwingungen"
python gscholar.py "Теория потенциала и ее применение к основным задачам математической физики"
python gscholar.py "Приближённые методы решения дифференциальных и интегральных уравнений"
python gscholar.py "О численном решении некоторых интегральных уравнений Фредгольма 1-го рода"
python gscholar.py "О численном решении пространственных задач теории потенциала"
python gscholar.py "О решении задач дифракции потенциалами простого слоя"
python gscholar.py "Решение двумерной задачи дифракции акустической волны на упругом теле методом потенциалов"
python gscholar.py "Acoustic and Electromagnetic Equations"
python gscholar.py "Strongly elliptic systems and boundary integral equations"
python gscholar.py "Обратные задачи рассеяния в акустике"
python gscholar.py "Мультипликативное управление в задаче рассеяния для уравнения Гельмгольца"
python gscholar.py "A weak bang-bang principle for the control of an exterior Robin problem"
python gscholar.py "Inverse scattering for shape and impedance"
python gscholar.py "Optimization methods in electromagnetic radiation"
python gscholar.py "Shape optimization for noise radiation problems"
python gscholar.py "Nonsmooth shape optimization applied to linear acoustic"
python gscholar.py "Diffraction d'une onde electromagnetique plane par un objet cylindrique non infiniment conducteur de section arbitraire"
python gscholar.py "Динамика русловых потоков и литодинамика прибрежной зоны моря"
python gscholar.py "The bedload function for sediment transportation in open channel flow"
python gscholar.py "The flow of cohesionless grains in fluids, Philos Trans"
python gscholar.py "Sand bed instability due to bed-load motion"
python gscholar.py "Mechanics of sediment transport of graded materials and fluvial sorting report (in Japanese and English)"
python gscholar.py "Sediment pick-up functions"
python gscholar.py "Saltation of uniform grains in air"
python gscholar.py "Study on hydraulic resistance and bedload transport rate in alluvial streams"
python gscholar.py "Речные наносы"
python gscholar.py "A sediment transport model for straight alluvial channels"
python gscholar.py "A theoretical model for saltating grains in water"
python gscholar.py "Mechanics of saltating grains"
python gscholar.py "Bedload transport on transverse slopes"
python gscholar.py "Gravel saltation"
python gscholar.py "A new vectorial bedload formulation and its application to the time evolution of straight river channels"
python gscholar.py "A model for the entrainment and transport of sediment grains of mixed sizes, shapes and densities"
python gscholar.py "Erosion and transport of bedload sediment"
python gscholar.py "Using Lagrangian particle saltation observations for bedload sediment transport modeling"
python gscholar.py "A dynamic boundary condition for bedload sediment transport in non-uniform, hydraulically rough turbulent boundary layers"
python gscholar.py "The grain-fluid interaction as a self-stabilizing mechanism in fluvial bedload transport"
python gscholar.py "Experiments on incipient canalizations of submarine fans"
python gscholar.py "Движение донных наносов под воздействием потока жидкости"
python gscholar.py "Движение сыпучей среды в придонном слое жидкости"
python gscholar.py "Вектор расхода наносов в турбулентном потоке над размываемым дном"
python gscholar.py "Двумерная модель транспорта донных наносов для рек с песчаным дном"
python gscholar.py "Formulae for bedload transport"
python gscholar.py "Постановка и решение задачи об устойчивости несвязного дна канала"
python gscholar.py "О Развитии возмущений песчаного дна канала"
python gscholar.py "Русловой процесс"
python gscholar.py "К теории движения взвешенных наносов"
python gscholar.py "Основы гидроморфологической теории руслового процесса"
python gscholar.py "Устойчивость русел рек и каналов"
python gscholar.py "Гидравлическое сопротивление естественных русел"
python gscholar.py "Неустойчивость донных волн в деформируемом русле"
python gscholar.py "Физика волн на поверхности сыпучей среды и жидкости"
python gscholar.py "Движение влекомых наносов"
python gscholar.py "Формирование поверхностного слоя металлов при электроискровом легировании"
python gscholar.py "Технологический процесс изменения исходных свойств металлических поверхностей электрическими импульсами"
python gscholar.py "Электродные материалы для электроискрового легирования"
python gscholar.py "Физико-химические основы процесса электроискрового легирования"
python gscholar.py "Электроискровое легирование металлических поверхностей"
python gscholar.py "Surface hardening of metals by spark discharge"
python gscholar.py "Electric spark toughening of cutting tools and steel components"
python gscholar.py "Электроискровое легирование рабочих поверхностей инструментов и деталей машин электродными материалами, полученными из минерального сырья"
python gscholar.py "Упрочнение поверхностей деталей комбинированными способами"
python gscholar.py "О механизме образования покрытий при электроискровом легировании металлических поверхностей"
python gscholar.py "Электроискровое легирование металлических поверхностей"
python gscholar.py "Физические основы электроискровой обработки металлов"
python gscholar.py "О физической природе электрической обработки металлов"
python gscholar.py "Формирование поверхностного слоя из переходных металлов на тантале и сталях при воздействии электрических разрядов"
python gscholar.py "Модель формирования покрытий при электроискровом легировании"
python gscholar.py "Электроискровая обработка токопроводящих материалов"
python gscholar.py "О физической природе эрозии и формирования поверхностного слоя при электроискровом легировании молибдена пористыми электродами железа"
python gscholar.py "Электрическая теория искровой эрозии металлов"
python gscholar.py "Динамическая теория выброса материала электрода коротким электрическим импульсом и закономерности образования ударных кратеров"
python gscholar.py "Роль факелов импульсного разряда в передаче энергии и эрозии электродов"
python gscholar.py "Современный уровень развития электроискровой обработки металлов и некоторые научные проблемы в этой области"
python gscholar.py "Электроискровое легирование металлических поверхностей"
python gscholar.py "Электроразведка: Справочник геофизика"
python gscholar.py "Электроразведка на современном этапе"
python gscholar.py "Modeling and Characterization of the Interaction of Electromagnetic Wave with Nanocomposites and Nanostructured Materials"
python gscholar.py "Вычислительные математика и техника в разведочной геофизике: Справочник геофизика"
python gscholar.py "Antje, Franke, Ralph-Uwe Borner and Klaus Spitzer. 2D Finite Element modelling of plane-wave diffusive time-harmonic electromagnetic fields using adaptive unstructured grids. Technische Universitat Bergakademie Freiberg, Institute of Geophysics, Freiberg, Germany. Proceedings of the 17th Workshop Hyderabad, India, October 18-23. - 2004."
python gscholar.py "A new computation method for a staggered grid of 3D EM field conservative modeling"
python gscholar.py "Fast Finite Volume Simulation of 3D Electromagnetic Problems with Highly Discontinuous Coefficients"
python gscholar.py "Трехмерные электромагнитные поля в двумерно-неоднородных средах"
python gscholar.py "Моделирование электромагнитных полей в слоистых средах с включениями"
python gscholar.py "Adaptive finite-element modeling using unstructured grids: The 2D magnetotelluric example"
python gscholar.py "An alternative algorithm for one-dimensional magnetotelluric response calculation"
python gscholar.py "A new methodology for the acquisition and processing of audio-magnetotelluric (AMT) data in the AMT dead band"
python gscholar.py "Principles of spatial surface electric field filtering in magnetotellurics: Electromagnetic array profiling (EMAP)"
python gscholar.py "Inversion of controlled source audio-frequency magnetotellurics data for a horizontally layered earth"
python gscholar.py "Математическое моделирование электромагнитных полей в трехмерно-неоднородных средах"
python gscholar.py "Rapid neuronet inversion of 2D magnetotelluric data for monitoring of geoelectrical section parameters"
python gscholar.py "Crack Sizing by Using Pulsed Eddy Cur-rent Technique and Neural Network"
python gscholar.py "An Improved Ant Colony Optimization Algorithm and its Application to Electromagnetic Devices Designs"
python gscholar.py "Using Genetic Algorithm to Reduce The Radar Cross Section of Three-Dimensional Anisotropic Impedance Object"
python gscholar.py "Microwave imaging of parallel perfectly conducting cylinders using real-coded genetic algorithm coupled with Newton-Kantorivitch method"
python gscholar.py "Microwave Imaging of Buried Inhomogeneous Objects Using Parallel Genetic Algorithm Combined With Fdtd Method"
python gscholar.py "Electro-magnetic Transverse Electric-Wave Inverse Scattering of an Imperfectly Conducting Cylinder by Genetic Algorithms"
python gscholar.py "Application of 2-D inversion with genetic algorithms to magnetotelluric data from geothermal areas"
python gscholar.py "2-D MT Inversion Using Genetic Algorithm"
python gscholar.py "Генетические алгоритмы решения обратных задач электромагнитного зондирования"
python gscholar.py "Inverse Algorithms for the GPR Assessment of Concrete Structures"
python gscholar.py "Simulational modeling of time-domain magnetic induction using parallel computational schemes: (I) in the Cartesian coordinates"
python gscholar.py "ГОСТ 18353-79. Контроль неразрушающий. Классификация видов и методов."
python gscholar.py "ГОСТ 23829-85. Контроль неразрушающий акустический. Термины и определения"
python gscholar.py "Справочник"
python gscholar.py "Справочник"
python gscholar.py "Справочник"
python gscholar.py "Справочник"
python gscholar.py "Справочник"
python gscholar.py "Справочник"
python gscholar.py "Справочник"
python gscholar.py "Справочник"
python gscholar.py "Акустические методы изучения микровключений и внутренних напряжений в монокристаллах ферритов"
python gscholar.py "Физическая акустика"
python gscholar.py "Resonant ultrasound spectroscopy to measure tensile strength and Rockwell C hardness"
python gscholar.py "Resonant ultrasound spectroscopy for discontinuity detection in both metallic and nonmetallic parts"
python gscholar.py "Прецизионные акустические измерения оптическими и емкостными методами"
python gscholar.py "Прецизионные методы измерения акустических величин твердых сред"
python gscholar.py "Прецизионные методы измерения акустических величин твердых сред"
python gscholar.py "Ультразвук и его применение в науке и технике"
python gscholar.py "связанной со спектром его собственных частот"
python gscholar.py "Прецизионный метод измерения коэффициента поглощения ультразвука в жидкостях на частотах 0,1 - 20 МГц"
python gscholar.py "Приборы для неразрушающего контроля материалов и изделий"
python gscholar.py "Influence of vearplate coupling lager thickens of ultra-sonic velocity measurements"
python gscholar.py "Resonance method for measurement of longitudinal and transverse ultrasonic wave velocities and their attenuation"
python gscholar.py "Физические основы спектрального метода измерения затухания ультразвуковых волн в материалах"
python gscholar.py "Прецизионные измерения скорости и затухания ультразвука в твердых телах"
python gscholar.py "Реализация резонансного метода измерения скорости и затухания ультразвуковых колебаний при наличии помехи"
python gscholar.py "Волны в слоистых средах"
python gscholar.py "Теория упругости"
python gscholar.py "Pickup and Delivery Problem with Time Windows"
python gscholar.py "Solomon, Francois Soumis"
python gscholar.py "Route Construction and Local Search Algorithms for the Vehicle Routing Problem with Time Windows"
python gscholar.py "Vehicle routing and scheduling whith dynamic trave times"
python gscholar.py "Dinamic and Stochastic Aspects in Vehicle Routing – A Literature Survey"
python gscholar.py "Heuristic Methods for Vehicle Routing Problem with Time Windows"
python gscholar.py "Tabu Search Heuristics for the Vehicle Routing Problem with Time Windows"
python gscholar.py "Metaheuristic Approaches for the Vehicle Routing Problem with Time Windows: A Survey"
python gscholar.py "A Tabu Search Heuristic for the Vehicle Routing Problem with Soft Time Windos"
python gscholar.py "A Parallel Tabu Search Heuristic for the Vehicle Routing Problem with Time Windos"
python gscholar.py "Parallel Tabu Search for Real-Time Vehicle Routing and Dispatching"
python gscholar.py "Эвристические и метаэвристические методы решения динамической транспортной задачи"
python gscholar.py "A Metaheuristic to Solve a Location-Routing Problem with Non-Linear Costs"
python gscholar.py "Parallel Solution Methods for Vehicle Routing Problems"
python gscholar.py "An improved ant colony system algorithm for the vehicle routing problem"
python gscholar.py "Implementation Of An Ant Colony System With Local Search For The Vehicle Routing Problem With Capacity And Time Windows (CVRPTW)"
python gscholar.py "Ant colony optimization techniques for the vehicle routing problem"
python gscholar.py "Applying the Ant System to the Vehicle Routing Problem"
python gscholar.py "Particle Swarm Optimization for Open Vehicle Routing Problem with Time Dependent Travel Time"
python gscholar.py "Алгоритмы решения экстремальных задач"
python gscholar.py "Introduction to Logistics Systems Planning and Control"
python gscholar.py "Artificial Intelligence in Transportation Information for Application Transportation"
python gscholar.py "Оптимизационные задачи производственно-транспортного планирования: Модели, методы, алгоритмы"
python gscholar.py "Нелинейные транспортные задачи на сетях"
python gscholar.py "Transportation problem with nonlinear side constraints a branch and bound approach"
python gscholar.py "A stationary nonlinear transport problem"
python gscholar.py "A Nonlinear Pricing Model with Lump-Sum Transportation Costs"
python gscholar.py "An Evolution Program for Non-Linear Transportation Problems"
python gscholar.py "Vehicle Dispatching at Seaport Container Terminals Using Evolutionary Algorithms"
python gscholar.py "Численное решение трехмерной стационарной задачи дифракции упругих волн на основе векторного интегрального уравнения Фредгольма I рода"
python gscholar.py "Genetic Algorithm for the Transportation Problem with Discontinuous Piecewise Linear Cost Function"
python gscholar.py "A Nonstandard Genetic Algorithm for the Nonlinear Transportation Problem"
python gscholar.py "Обобщённые решения интегральных уравнений скалярной задачи дифракции"
python gscholar.py "Методы потенциала в теории упругости"
python gscholar.py "Численное решение трехмерной стационарной задачи дифракции упругих волн"
python gscholar.py "Численное решение трехмерной стационарной задачи дифракции акустических волн"
python gscholar.py "An Evolution Program for Non-Linear Transportation Problems"
